"""Fix user relationships and cascades

Revision ID: 247e2910ede8
Revises: 937497d47057
Create Date: 2026-01-20 17:31:42.131459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247e2910ede8'
down_revision: Union[str, Sequence[str], None] = '937497d47057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_mode'), table_name='statistics')
    op.drop_constraint(op.f('statistics_userID_fkey'), 'statistics', type_='foreignkey')
    op.create_foreign_key(None, 'statistics', 'users', ['userID'], ['userID'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_leaderboard_userID_fkey'), 'user_leaderboard', type_='foreignkey')
    op.create_foreign_key(None, 'user_leaderboard', 'users', ['userID'], ['userID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_leaderboard', type_='foreignkey')
    op.create_foreign_key(op.f('user_leaderboard_userID_fkey'), 'user_leaderboard', 'users', ['userID'], ['userID'])
    op.drop_constraint(None, 'statistics', type_='foreignkey')
    op.create_foreign_key(op.f('statistics_userID_fkey'), 'statistics', 'users', ['userID'], ['userID'])
    op.create_index(op.f('ix_statistics_mode'), 'statistics', ['mode'], unique=False)
    # ### end Alembic commands ###
