"""add startat to dailygame

Revision ID: 89e37fc0f0f0
Revises: 021255dc046e
Create Date: 2026-01-10 21:41:11.658362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e37fc0f0f0'
down_revision: Union[str, Sequence[str], None] = '021255dc046e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_games', sa.Column('startAt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_games', 'startAt')
    # ### end Alembic commands ###
