"""changed field names of song for less ambiguity

Revision ID: 937497d47057
Revises: e38c25351dff
Create Date: 2026-01-12 17:21:00.951475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937497d47057'
down_revision: Union[str, Sequence[str], None] = 'e38c25351dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('shareLink', sa.String(), nullable=False))
    op.add_column('songs', sa.Column('audioLink', sa.String(), nullable=False))
    op.drop_constraint(op.f('songs_audio_key'), 'songs', type_='unique')
    op.drop_constraint(op.f('songs_link_key'), 'songs', type_='unique')
    op.create_unique_constraint(None, 'songs', ['shareLink'])
    op.create_unique_constraint(None, 'songs', ['audioLink'])
    op.drop_column('songs', 'link')
    op.drop_column('songs', 'audio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('audio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('songs', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'songs', type_='unique')
    op.create_unique_constraint(op.f('songs_link_key'), 'songs', ['link'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('songs_audio_key'), 'songs', ['audio'], postgresql_nulls_not_distinct=False)
    op.drop_column('songs', 'audioLink')
    op.drop_column('songs', 'shareLink')
    # ### end Alembic commands ###
