"""added mode to dailygame for has played checks and duration to song

Revision ID: c9c4b7055022
Revises: 89e37fc0f0f0
Create Date: 2026-01-10 23:32:16.446390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9c4b7055022'
down_revision: Union[str, Sequence[str], None] = '89e37fc0f0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('mode', postgresql.ENUM('original', 'daily', name='modes'), nullable=False))
    op.create_index(op.f('ix_game_sessions_mode'), 'game_sessions', ['mode'], unique=False)
    op.add_column('songs', sa.Column('duration', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_songs_duration'), 'songs', ['duration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_duration'), table_name='songs')
    op.drop_column('songs', 'duration')
    op.drop_index(op.f('ix_game_sessions_mode'), table_name='game_sessions')
    op.drop_column('game_sessions', 'mode')
    # ### end Alembic commands ###
