"""add wsgamesession to gamesession

Revision ID: d5e0f1789798
Revises: c9c4b7055022
Create Date: 2026-01-11 14:11:40.745152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e0f1789798'
down_revision: Union[str, Sequence[str], None] = 'c9c4b7055022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('wsGameSessionID', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_game_sessions_wsGameSessionID'), 'game_sessions', ['wsGameSessionID'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_sessions_wsGameSessionID'), table_name='game_sessions')
    op.drop_column('game_sessions', 'wsGameSessionID')
    # ### end Alembic commands ###
