"""initial schema

Revision ID: e38c25351dff
Revises: 
Create Date: 2026-01-12 13:37:23.322276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38c25351dff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artistID', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('artistID')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_table('leaderboards',
    sa.Column('mode', postgresql.ENUM('original', 'daily', name='modes'), nullable=False),
    sa.Column('period', postgresql.ENUM('daily', 'weekly', 'monthly', 'all_time', name='periods'), nullable=False),
    sa.PrimaryKeyConstraint('mode', 'period')
    )
    op.create_table('songs',
    sa.Column('songID', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('releaseYear', sa.Integer(), nullable=False),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('songID'),
    sa.UniqueConstraint('audio'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_songs_album'), 'songs', ['album'], unique=False)
    op.create_index(op.f('ix_songs_duration'), 'songs', ['duration'], unique=False)
    op.create_index(op.f('ix_songs_releaseYear'), 'songs', ['releaseYear'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_table('users',
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_games',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startAt', sa.Integer(), nullable=False),
    sa.Column('songID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['songID'], ['songs.songID'], ),
    sa.PrimaryKeyConstraint('date', 'songID')
    )
    op.create_table('song__artist',
    sa.Column('songID', sa.UUID(), nullable=False),
    sa.Column('artistID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artistID'], ['artists.artistID'], ),
    sa.ForeignKeyConstraint(['songID'], ['songs.songID'], ),
    sa.PrimaryKeyConstraint('songID', 'artistID')
    )
    op.create_table('statistics',
    sa.Column('mode', postgresql.ENUM('original', 'daily', name='modes'), nullable=False),
    sa.Column('gamesPlayed', sa.Integer(), nullable=False),
    sa.Column('winCount', sa.Integer(), nullable=False),
    sa.Column('currentStreak', sa.Integer(), nullable=False),
    sa.Column('maximumStreak', sa.Integer(), nullable=False),
    sa.Column('guesses1', sa.Integer(), nullable=False),
    sa.Column('guesses2', sa.Integer(), nullable=False),
    sa.Column('guesses3', sa.Integer(), nullable=False),
    sa.Column('guesses4', sa.Integer(), nullable=False),
    sa.Column('guesses5', sa.Integer(), nullable=False),
    sa.Column('guesses6', sa.Integer(), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('mode', 'userID')
    )
    op.create_index(op.f('ix_statistics_currentStreak'), 'statistics', ['currentStreak'], unique=False)
    op.create_index(op.f('ix_statistics_gamesPlayed'), 'statistics', ['gamesPlayed'], unique=False)
    op.create_index(op.f('ix_statistics_guesses1'), 'statistics', ['guesses1'], unique=False)
    op.create_index(op.f('ix_statistics_guesses2'), 'statistics', ['guesses2'], unique=False)
    op.create_index(op.f('ix_statistics_guesses3'), 'statistics', ['guesses3'], unique=False)
    op.create_index(op.f('ix_statistics_guesses4'), 'statistics', ['guesses4'], unique=False)
    op.create_index(op.f('ix_statistics_guesses5'), 'statistics', ['guesses5'], unique=False)
    op.create_index(op.f('ix_statistics_guesses6'), 'statistics', ['guesses6'], unique=False)
    op.create_index(op.f('ix_statistics_maximumStreak'), 'statistics', ['maximumStreak'], unique=False)
    op.create_index(op.f('ix_statistics_mode'), 'statistics', ['mode'], unique=False)
    op.create_index(op.f('ix_statistics_winCount'), 'statistics', ['winCount'], unique=False)
    op.create_table('user_leaderboard',
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('mode', postgresql.ENUM('original', 'daily', name='modes'), nullable=False),
    sa.Column('period', postgresql.ENUM('daily', 'weekly', 'monthly', 'all_time', name='periods'), nullable=False),
    sa.Column('numberOfWins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mode', 'period'], ['leaderboards.mode', 'leaderboards.period'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'mode', 'period')
    )
    op.create_table('game_sessions',
    sa.Column('gameSessionID', sa.UUID(), nullable=False),
    sa.Column('wsGameSessionID', sa.UUID(), nullable=True),
    sa.Column('mode', postgresql.ENUM('original', 'daily', name='modes'), nullable=False),
    sa.Column('result', postgresql.ENUM('win', 'lose', name='results'), nullable=False),
    sa.Column('userID', sa.UUID(), nullable=False),
    sa.Column('songID', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['songID', 'date'], ['daily_games.songID', 'daily_games.date'], ),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('gameSessionID')
    )
    op.create_index(op.f('ix_game_sessions_date'), 'game_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_game_sessions_mode'), 'game_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_game_sessions_result'), 'game_sessions', ['result'], unique=False)
    op.create_index(op.f('ix_game_sessions_songID'), 'game_sessions', ['songID'], unique=False)
    op.create_index(op.f('ix_game_sessions_userID'), 'game_sessions', ['userID'], unique=False)
    op.create_index(op.f('ix_game_sessions_wsGameSessionID'), 'game_sessions', ['wsGameSessionID'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_sessions_wsGameSessionID'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_userID'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_songID'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_result'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_mode'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_date'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('user_leaderboard')
    op.drop_index(op.f('ix_statistics_winCount'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_mode'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_maximumStreak'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses6'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses5'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses4'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses3'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses2'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_guesses1'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_gamesPlayed'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_currentStreak'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_table('song__artist')
    op.drop_table('daily_games')
    op.drop_table('users')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_releaseYear'), table_name='songs')
    op.drop_index(op.f('ix_songs_duration'), table_name='songs')
    op.drop_index(op.f('ix_songs_album'), table_name='songs')
    op.drop_table('songs')
    op.drop_table('leaderboards')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
